export { TestappComponent } from "./testapp/testapp.component";
export { MenuComponent } from "./menu/menu.component";
export { HouseComponent } from "./house/house.component";
export { OfficeComponent } from "./office/office.component";
export { EventsComponent } from "./events/events.component";
export { CommercialComponent } from "./commercial/commercial.component";
export { CommercialoneComponent } from "./commercialone/commercialone.component";
export { CommercialtwoComponent } from "./commercialtwo/commercialtwo.component";
export { CommercialthreeComponent } from "./commercialthree/commercialthree.component";
export { CommercialfourComponent } from "./commercialfour/commercialfour.component";
export { CommercialfiveComponent } from "./commercialfive/commercialfive.component";
export { ContactComponent } from "./contact/contact.component";
export { CarpetComponent } from "./carpet/carpet.component";
export { CovidComponent } from "./covid/covid.component";
export { QuoteComponent } from "./quote/quote.component";
export { ProjectsComponent } from "./projects/projects.component";
export { PrjtsComponent } from "./prjts/prjts.component";
export { ProjectdetailComponent } from "./projectdetail/projectdetail.component";

export { ProjectoneComponent } from "./projectone/projectone.component";
export { ProjecttwoComponent } from "./projecttwo/projecttwo.component";
export { ProjectthreeComponent } from "./projectthree/projectthree.component";
export { ProjectfourComponent } from "./projectfour/projectfour.component";
export { GalleryComponent } from "./gallery/gallery.component";
// export { FruitbannerboxComponent } from "./fruitbannerbox/fruitbannerbox.component";

export { TopbarComponent } from "./topbar/topbar.component";
export { CheckoutComponent } from "./checkout/checkout.component";
export { FooterComponent } from "./footer/footer.component";
export { CompanyComponent } from "./company/company.component";
export { PagoComponent } from "./pago/pago.component";
export { PrecheckComponent } from "./precheck/precheck.component";
